name: Generate Dynamic Matrix

on:
  push:
    branches:
      - main


jobs:
  GenerateMatrix:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Matrix JSON
        id: generate-matrix-json
        run: |
          echo "::set-output name=matrix::${{ toJSON(['12', '14', '16']) }}"

    outputs:
      matrix: ${{ steps.generate-matrix-json.outputs.matrix }}



  ShowMatrix:
    runs-on: ubuntu-latest
    needs:
      - GenerateMatrix
    steps:
      - run: |
          echo "Matrix: ${{ toJSON(needs.GenerateMatrix.outputs) }}"


  UseMatrix:
    needs:
      - GenerateMatrix
    strategy:
      matrix:
        nodeVersion: ${{ fromJSON(needs.GenerateMatrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        use: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}

      - name: Show Node Version
        run: node -v

